### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Siujohnjai** [DurstewitzLab/GTF-shPLRNN#1]
Hi, 

Do you have a python version of your code?

**Comment by flo-he** [comment]
Hey,

there is only a very minimal training routine written in PyTorch from our tutorial at the CNS2023 in [this jupyter notebook](https://github.com/DurstewitzLab/CNS-2023/blob/main/CNS2023_tutorial.ipynb). This does e.g. not feature aGTF.
